### ISSUE TITLE
File not found … in any of the following include paths …

### ISSUE THREAD

**Issue by simonc** [billybonks/broccoli-stylelint#208]
Hi there!

I'm trying to use broccoli-stylelint in my build and I can't manage to get it to play nice with sass compilation.

Here is the code that works
```js
import funnel from 'broccoli-funnel';
import merge from 'broccoli-merge-trees';

import Sass from 'sass';
import SassSourceMaps from 'broccoli-sass-source-maps';

const appRoot = "_assets";
const compileSass = SassSourceMaps(Sass);

let css = funnel(`${appRoot}/stylesheets`);

css = compileSass(
  [css, 'node_modules/bootstrap'],
  'style.scss',
  'assets/style.css',
  {
    sourceMap: false,
    sourceMapContents: true,
    annotation: 'SCSS Files'
  }
);

export default () => merge([css]);
```

Once I try adding StyleLint it doesn't work anymore:

```js
import funnel from 'broccoli-funnel';
import merge from 'broccoli-merge-trees';

import Sass from 'sass';
import SassSourceMaps from 'broccoli-sass-source-maps';

import StyleLint from 'broccoli-stylelint';

const appRoot = "_assets";
const compileSass = SassSourceMaps(Sass);

let css = StyleLint.create(`${appRoot}/stylesheets`, { disableTestGenerator: true });

css = compileSass(
  [css, 'node_modules/bootstrap'],
  'style.scss',
  'assets/style.css',
  {
    sourceMap: false,
    sourceMapContents: true,
    annotation: 'SCSS Files'
  }
);

export default () => merge([css]);
```
I get an error stating
```
build failure
File not found: style.scss
in any of the following include paths:
  /var/folders/90/y7lt76pd6jj7sp0kr3mcv5600000gn/T/broccoli-46374vzb1rEHIyaTb/out-1-broccoli_persistent_filter_broccoli_style_lint
  node_modules/bootstrap
        at SassCompiler (SCSS Files)
-~- created here: -~-
    at SassCompiler.Plugin (/Users/simonc/my-project/node_modules/broccoli-plugin/index.js:7:31)
    at SassCompiler.CachingWriter [as constructor] (/Users/simonc/my-project/node_modules/broccoli-caching-writer/index.js:18:10)
    at new SassCompiler (/Users/simonc/my-project/node_modules/broccoli-sass-source-maps/index.js:21:19)
    at SassCompiler (/Users/simonc/my-project/node_modules/broccoli-sass-source-maps/index.js:16:51)
    at Object.<anonymous> (/Users/simonc/my-project/Brocfile.js:100:7)
    at Generator.next (<anonymous>)
    at bl (/Users/simonc/my-project/node_modules/esm/esm.js:1:245412)
    at kl (/Users/simonc/my-project/node_modules/esm/esm.js:1:247659)
    at Object.u (/Users/simonc/my-project/node_modules/esm/esm.js:1:287740)
    at Object.o (/Users/simonc/my-project/node_modules/esm/esm.js:1:287137)
-~- (end) -~-


Stack Trace and Error Report: /var/folders/90/y7lt76pd6jj7sp0kr3mcv5600000gn/T/error.dump.5a470b96cbe9e189fa5c04355ddf4427.log
✨  Done in 1.86s.
```

Is there something I'm doing wrong? Is there something  broken?

Thanks! ❤️

**Comment by billybonks** [comment]
Hey sorry for the extremely late reply here. do you have a repo i can play with ?

**Comment by simonc** [comment]
Hi @billybonks. I just created a repository reproducing the issue.

https://github.com/simonc/debug-broccoli-stylelint

I attempted to approaches, you can find them here

https://github.com/simonc/debug-broccoli-stylelint/blob/master/Brocfile.js#L52-L64

Thanks.

**Comment by simonc** [comment]
No activity in more than a year. I'm closing this 🙂
